version: "{build}"

cache:
  - vendor/bundle

environment:
  matrix:
    - RUBY_VERSION: 22
    - RUBY_VERSION: 23

install:
  - ps: Invoke-WebRequest -Uri https://technet.microsoft.com/en-us/sysinternals/bb896655.aspx -OutFile C:\handle.zip; Expand-Archive c:\handle.zip -dest c:\
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - gem install bundler
  - bundle install --path vendor/bundle

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake spec

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
